import { addDaysToKey } from "../../../shared/time/dateKey.js";
import { normalizeEventInput } from "../model/event.js";
import { normalizeException } from "../model/exception.js";
import { normalizeTiming } from "../model/timing.js";
import { generateRecurrenceAnchors } from "../recurrence/expandRecurrence.js";
import { parseOccurrenceId } from "../recurrence/occurrenceIdentity.js";

function context(state, occurrenceId, options) {
  const { seriesId, anchor } = parseOccurrenceId(occurrenceId);
  const series = (state.events || []).find((event) => event.id === seriesId);
  if (!series) throw new Error(`calendar series ${seriesId} was not found`);
  if (options.expectedSeriesRevision != null && options.expectedSeriesRevision !== (series.revision || 1)) {
    throw new Error(`series revision conflict: expected ${options.expectedSeriesRevision}`);
  }
  const date = anchor.slice(0, 10);
  if (!generateRecurrenceAnchors(series, date, addDaysToKey(date, 1)).includes(anchor)) {
    throw new Error(`${occurrenceId} is not generated by series ${seriesId}`);
  }
  return { series, seriesId, anchor };
}

function putException(state, exception, anchor) {
  const previous = structuredClone(state.eventExceptions || []);
  const nextExceptions = previous.filter((item) => item.seriesId !== exception.seriesId || item.recurrenceAnchor !== anchor || item.type === "added");
  nextExceptions.push(exception);
  return {
    state: { ...state, eventExceptions: nextExceptions },
    exception,
    removed: { kind: "event-exceptions", eventExceptions: previous },
    domainEvents: [{ type: "OccurrenceChanged", aggregateId: exception.seriesId, occurrenceId: exception.occurrenceId }],
  };
}

function idOption(options) {
  if (typeof options.id !== "string" || !options.id) throw new TypeError("exception command requires an ID");
  return options.id;
}

export function modifyOccurrence(state, occurrenceId, patch, options = {}) {
  const { series, seriesId, anchor } = context(state, occurrenceId, options);
  const exception = normalizeException({
    id: idOption(options), type: "modified", seriesId, occurrenceId,
    recurrenceAnchor: anchor, patch, revision: 1,
  }, series);
  return putException(state, exception, anchor);
}

export function moveOccurrence(state, occurrenceId, timing, options = {}) {
  const { series, seriesId, anchor } = context(state, occurrenceId, options);
  const exception = normalizeException({
    id: idOption(options), type: "moved", seriesId, occurrenceId,
    recurrenceAnchor: anchor, timing: normalizeTiming(timing),
    ...(options.patch ? { patch: options.patch } : {}), revision: 1,
  }, series);
  return putException(state, exception, anchor);
}

export function cancelOccurrence(state, occurrenceId, options = {}) {
  const { series, seriesId, anchor } = context(state, occurrenceId, options);
  const exception = normalizeException({
    id: idOption(options), type: "cancelled", seriesId, occurrenceId,
    recurrenceAnchor: anchor, revision: 1,
  }, series);
  return putException(state, exception, anchor);
}

export function addOccurrence(state, seriesId, eventInput, options = {}) {
  const series = (state.events || []).find((event) => event.id === seriesId);
  if (!series) throw new Error(`calendar series ${seriesId} was not found`);
  const occurrenceId = options.occurrenceId;
  if (typeof occurrenceId !== "string" || !occurrenceId) throw new TypeError("added occurrence requires an immutable occurrence ID");
  if ((state.eventExceptions || []).some((item) => item.occurrenceId === occurrenceId)) throw new Error(`occurrence ${occurrenceId} already exists`);
  const event = normalizeEventInput({ ...eventInput, recurrence: null });
  const exception = normalizeException({
    id: idOption(options), type: "added", seriesId, occurrenceId, event, revision: 1,
  }, series);
  return {
    state: { ...state, eventExceptions: [...(state.eventExceptions || []), exception] },
    exception,
    removed: { kind: "event-exceptions", eventExceptions: structuredClone(state.eventExceptions || []) },
    domainEvents: [{ type: "OccurrenceAdded", aggregateId: seriesId, occurrenceId }],
  };
}

export function restoreOccurrence(state, snapshot) {
  if (snapshot?.kind !== "event-exceptions" || !Array.isArray(snapshot.eventExceptions)) {
    throw new TypeError("restoreOccurrence requires an exact exception snapshot");
  }
  return {
    state: { ...state, eventExceptions: structuredClone(snapshot.eventExceptions) },
    exception: null,
    removed: null,
    domainEvents: [{ type: "OccurrenceRestored" }],
  };
}
