import { addDaysToKey } from "../../../shared/time/dateKey.js";
import { normalizeEventInput } from "../model/event.js";
import { normalizeRecurrenceRule } from "../model/recurrenceRule.js";
import { generateRecurrenceAnchors, timingAtAnchor } from "../recurrence/expandRecurrence.js";
import { makeOccurrenceId, parseOccurrenceId } from "../recurrence/occurrenceIdentity.js";
import { assertAliasSet } from "../recurrence/splitSeries.js";

export function changeRecurrence(state, seriesId, rule, options = {}) {
  const series = (state.events || []).find((event) => event.id === seriesId);
  if (!series) throw new Error(`calendar series ${seriesId} was not found`);
  if (options.expectedRevision != null && options.expectedRevision !== (series.revision || 1)) throw new Error("series revision conflict");
  const recurrence = normalizeRecurrenceRule(rule, series.timing);
  const event = normalizeEventInput({ ...series, recurrence, revision: (series.revision || 1) + 1 });
  return {
    state: { ...state, events: state.events.map((item) => item.id === seriesId ? event : item) },
    event,
    removed: { kind: "planner-state", state: structuredClone(state) },
    domainEvents: [{ type: "RecurrenceChanged", aggregateId: seriesId }],
  };
}

export function splitSeries(state, occurrenceId, changes = {}, options = {}) {
  const { seriesId, anchor } = parseOccurrenceId(occurrenceId);
  const series = (state.events || []).find((event) => event.id === seriesId);
  if (!series || !series.recurrence) throw new Error(`recurring calendar series ${seriesId} was not found`);
  const newSeriesId = options.newSeriesId;
  if (typeof newSeriesId !== "string" || !newSeriesId) throw new TypeError("split requires a new immutable series ID");
  if (state.events.some((event) => event.id === newSeriesId)) throw new Error(`calendar series ${newSeriesId} already exists`);
  if (options.expectedRevision != null && options.expectedRevision !== (series.revision || 1)) throw new Error("series revision conflict");

  const splitDate = anchor.slice(0, 10);
  const anchorsThroughSplit = generateRecurrenceAnchors(series, series.timing.kind === "all-day" ? series.timing.startDate : series.timing.startLocal.slice(0, 10), addDaysToKey(splitDate, 1));
  const splitIndex = anchorsThroughSplit.indexOf(anchor);
  if (splitIndex < 0) throw new Error(`${occurrenceId} is not generated by series ${seriesId}`);

  const oldRule = normalizeRecurrenceRule(series.recurrence, series.timing);
  const previousCount = splitIndex;
  const oldRecurrence = { ...oldRule };
  const newRecurrence = { ...oldRule };
  let futureAnchors = [anchor];
  if (oldRule.count) {
    oldRecurrence.count = previousCount;
    newRecurrence.count = oldRule.count - previousCount;
    const generousEnd = addDaysToKey(splitDate, Math.min(100_000, oldRule.count * oldRule.interval * 370));
    futureAnchors = generateRecurrenceAnchors(series, splitDate, generousEnd, newRecurrence.count);
  } else {
    const previousAnchor = anchorsThroughSplit[splitIndex - 1];
    oldRecurrence.until = previousAnchor || addDaysToKey(splitDate, -1);
    delete oldRecurrence.count;
  }
  if (previousCount === 0) {
    futureAnchors = oldRule.count
      ? generateRecurrenceAnchors(series, splitDate, addDaysToKey(splitDate, Math.min(100_000, oldRule.count * oldRule.interval * 370)), oldRule.count)
      : [anchor];
  }

  const splitTiming = timingAtAnchor(series.timing, anchor);
  if (!splitTiming) throw new Error("split occurrence falls in a skipped local time");
  const oldEvent = previousCount > 0 ? normalizeEventInput({ ...series, recurrence: oldRecurrence, revision: (series.revision || 1) + 1 }) : null;
  const newEvent = normalizeEventInput({
    ...series,
    ...changes,
    id: newSeriesId,
    timing: changes.timing || splitTiming,
    recurrence: changes.recurrence ? normalizeRecurrenceRule(changes.recurrence, changes.timing || splitTiming) : newRecurrence,
    revision: 1,
  });

  const aliasAnchors = new Set(futureAnchors);
  const aliases = futureAnchors.map((futureAnchor) => ({
    from: makeOccurrenceId(seriesId, futureAnchor),
    to: makeOccurrenceId(newSeriesId, futureAnchor),
  }));
  const eventExceptions = (state.eventExceptions || []).map((exception) => {
    const future = exception.seriesId === seriesId
      && (exception.recurrenceAnchor
        ? exception.recurrenceAnchor >= anchor
        : exception.type === "added"
          && (exception.event.timing.kind === "all-day" ? exception.event.timing.startDate : exception.event.timing.startLocal.slice(0, 10)) >= splitDate);
    if (!future) return exception;
    if (exception.recurrenceAnchor) aliasAnchors.add(exception.recurrenceAnchor);
    return {
      ...exception,
      seriesId: newSeriesId,
      occurrenceId: exception.recurrenceAnchor ? makeOccurrenceId(newSeriesId, exception.recurrenceAnchor) : exception.occurrenceId,
      revision: (exception.revision || 1) + 1,
    };
  });
  for (const futureAnchor of aliasAnchors) {
    if (!aliases.some((alias) => alias.from === makeOccurrenceId(seriesId, futureAnchor))) {
      aliases.push({ from: makeOccurrenceId(seriesId, futureAnchor), to: makeOccurrenceId(newSeriesId, futureAnchor) });
    }
  }
  const occurrenceAliases = [...(state.occurrenceAliases || []), ...aliases];
  assertAliasSet(occurrenceAliases);
  const events = [
    ...state.events.filter((event) => event.id !== seriesId),
    ...(oldEvent ? [oldEvent] : []),
    newEvent,
  ];
  return {
    state: { ...state, events, eventExceptions, occurrenceAliases },
    event: newEvent,
    removed: { kind: "planner-state", state: structuredClone(state) },
    aliases,
    domainEvents: [{ type: "SeriesSplit", aggregateId: seriesId, newAggregateId: newSeriesId, occurrenceId }],
  };
}
